# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20180701_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='addressid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='uid',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
