# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
